# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09c40a408b6f0af00105599e53d6f309ed34c3310ed0c5cbf2768783e13722dfbc3bf366aa8bf5185bfde7bd036aa4ff45dbbd7d03c6fe48f08b32de30f627d5

test:
  secret_key_base: 2a6ec0b8ed56fcf368669be3dbec73eaf5f3e89663e33b60d9b8a020d75dd70b1cf196b166582c0b6e22cd507462d2b49022dc1c53e9ee364bcca98a01655ed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
